# Generated by Django 5.1.4 on 2025-11-04 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('id', models.AutoField(help_text='Internal database identifier', primary_key=True, serialize=False)),
                ('global_id', models.CharField(db_index=True, help_text='Persistent global identifier generated from source, time, and location', max_length=255, null=True, unique=True)),
                ('source_id', models.CharField(blank=True, help_text='Original event identifier provided by the source catalog', max_length=255, null=True)),
                ('source', models.CharField(blank=True, help_text='Original data provider that published this event record (e.g., USGS, IGN, EMSC)', max_length=255, null=True)),
                ('origin_time', models.DateTimeField(help_text='Event origin time in UTC (ISO 8601 format)')),
                ('latitude', models.FloatField(help_text='Epicentral latitude in decimal degrees')),
                ('longitude', models.FloatField(help_text='Epicentral longitude in decimal degrees')),
                ('magnitude', models.FloatField(help_text='Reported event magnitude value')),
                ('mag_type', models.CharField(blank=True, help_text='Type of magnitude reported (e.g., Mw, ML, Mb)', max_length=16, null=True)),
                ('depth_km', models.FloatField(blank=True, help_text='Focal depth of the event in kilometers', null=True)),
                ('place_name', models.CharField(blank=True, help_text='Nearest known place or region as reported by the source', max_length=255, null=True)),
                ('origin_country', models.CharField(blank=True, help_text='Country determined from epicentral coordinates', max_length=255, null=True)),
                ('tectonic_plate', models.CharField(blank=True, help_text='Name of the tectonic plate where the event occurred', max_length=255, null=True)),
                ('affected_countries', models.JSONField(blank=True, default=list, help_text='List of countries potentially affected by the event or its intensity contours')),
                ('tsunami', models.BooleanField(default=False, help_text='Indicates whether a tsunami was reported or associated with the event')),
                ('has_curves', models.BooleanField(default=False, help_text='True if the event has associated intensity (shakemap) curves')),
                ('updated_time', models.DateTimeField(blank=True, help_text='Timestamp of the last update received from the source feed (UTC)', null=True)),
                ('retrieved_time', models.DateTimeField(blank=True, help_text='Timestamp when the event was retrieved by the local acquisition system (UTC)', null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Original raw JSON record from the source feed for reproducibility and provenance tracking', null=True)),
                ('duplicate_of', models.ForeignKey(blank=True, help_text='Reference to the canonical event if this record is classified as a duplicate of another', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='api.earthquake')),
            ],
            options={
                'verbose_name': 'Earthquake',
                'verbose_name_plural': 'Earthquakes',
            },
        ),
        migrations.CreateModel(
            name='DuplicateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.FloatField(help_text='Difference in origin time between the canonical and duplicate events (seconds)')),
                ('dd', models.FloatField(help_text='Epicentral distance between the canonical and duplicate events (kilometers)')),
                ('dm', models.FloatField(help_text='Magnitude difference between the canonical and duplicate events')),
                ('canonical', models.ForeignKey(help_text='Reference to the canonical event representing this duplicate cluster', on_delete=django.db.models.deletion.CASCADE, related_name='canonical_links', to='api.earthquake')),
                ('duplicate', models.ForeignKey(help_text='Reference to the secondary event considered a duplicate of the canonical one', on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_links', to='api.earthquake')),
            ],
            options={
                'verbose_name': 'Duplicate link',
                'verbose_name_plural': 'Duplicate links',
            },
        ),
        migrations.CreateModel(
            name='IntensityCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.FloatField(help_text='Intensity level (MMI value) represented by this contour')),
                ('coordinates', models.JSONField(help_text='List of polygon coordinates defining the contour geometry in GeoJSON format')),
                ('earthquake', models.ForeignKey(help_text='Reference to the parent earthquake event', on_delete=django.db.models.deletion.CASCADE, related_name='intensity_curves', to='api.earthquake')),
            ],
        ),
        migrations.AddConstraint(
            model_name='earthquake',
            constraint=models.UniqueConstraint(fields=('global_id',), name='unique_global_identifier'),
        ),
    ]
