# Generated by Django 5.1.4 on 2025-11-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_country_plate_earthquake_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.BooleanField(default=False)),
                ('last_sync_start', models.DateTimeField(blank=True, help_text='UTC timestamp marking the beginning of the last synchronization window', null=True)),
                ('last_sync_end', models.DateTimeField(blank=True, help_text='UTC timestamp marking the end of the last synchronization window', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='UTC timestamp of the most recent synchronization process', null=True)),
            ],
            options={
                'verbose_name': 'Synchronization state',
                'verbose_name_plural': 'Synchronization states',
                'db_table': 'sync_state',
            },
        ),
        migrations.AlterField(
            model_name='duplicatelink',
            name='dd',
            field=models.FloatField(help_text='Epicentral distance between canonical and duplicate events (kilometers)'),
        ),
        migrations.AlterField(
            model_name='duplicatelink',
            name='dm',
            field=models.FloatField(help_text='Magnitude difference between canonical and duplicate events'),
        ),
        migrations.AlterField(
            model_name='duplicatelink',
            name='dt',
            field=models.FloatField(help_text='Difference in origin time between canonical and duplicate events (seconds)'),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='global_id',
            field=models.CharField(db_index=True, help_text='Persistent global identifier generated from source and original identifier', max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='earthquake',
            index=models.Index(fields=['origin_time'], name='terremotos__origin__bc8efd_idx'),
        ),
        migrations.AddIndex(
            model_name='earthquake',
            index=models.Index(fields=['retrieved_time'], name='terremotos__retriev_1e2dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='earthquake',
            index=models.Index(fields=['source'], name='terremotos__source_8540b2_idx'),
        ),
        migrations.AddIndex(
            model_name='syncstate',
            index=models.Index(fields=['last_run_at'], name='sync_state_last_ru_59c380_idx'),
        ),
    ]
