# Generated by Django 5.1.4 on 2025-11-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_syncstate_alter_duplicatelink_dd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquake',
            name='affected_countries',
            field=models.JSONField(blank=True, default=list, help_text='List of countries potentially affected by the event or its intensity contours', null=True),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='global_id',
            field=models.CharField(db_index=True, help_text='Persistent global identifier generated from source and original identifier', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='has_curves',
            field=models.BooleanField(default=False, help_text='True if the event has associated intensity (shakemap) curves', null=True),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='magnitude',
            field=models.FloatField(help_text='Reported event magnitude value', null=True),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='source',
            field=models.CharField(blank=True, help_text='Original data provider that published this event record (e.g., USGS, IGN, EMSC)', max_length=255),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='source_id',
            field=models.CharField(blank=True, help_text='Original event identifier provided by the source catalog', max_length=255),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='tsunami',
            field=models.BooleanField(default=False, help_text='Indicates whether a tsunami was reported or associated with the event', null=True),
        ),
    ]
