# Generated by Django 5.1.4 on 2025-11-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_earthquake_affected_countries_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='earthquake',
            new_name='api_earthqu_origin__3d963c_idx',
            old_name='terremotos__origin__bc8efd_idx',
        ),
        migrations.RenameIndex(
            model_name='earthquake',
            new_name='api_earthqu_retriev_b8a51f_idx',
            old_name='terremotos__retriev_1e2dd6_idx',
        ),
        migrations.RenameIndex(
            model_name='earthquake',
            new_name='api_earthqu_source_b1d697_idx',
            old_name='terremotos__source_8540b2_idx',
        ),
    ]
